In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression


In [4]:
data=pd.read_csv("real_estate_price_size_year_view (2).csv")
data

price     size  year         view
0   234314.144   643.09  2015  No sea view
1   228581.528   656.22  2009  No sea view
2   281626.336   487.29  2018     Sea view
3   401255.608  1504.75  2015  No sea view
4   458674.256  1275.46  2009     Sea view
..         ...      ...   ...          ...
95  252460.400   549.80  2009     Sea view
96  310522.592  1037.44  2009  No sea view
97  383635.568  1504.75  2006  No sea view
98  225145.248   648.29  2015  No sea view
99  274922.856   705.29  2006     Sea view

[100 rows x 4 columns]

In [5]:
data['view']=data['view'].map({'No sea view':0,'Sea view':1})

In [6]:
data

price     size  year  view
0   234314.144   643.09  2015     0
1   228581.528   656.22  2009     0
2   281626.336   487.29  2018     1
3   401255.608  1504.75  2015     0
4   458674.256  1275.46  2009     1
..         ...      ...   ...   ...
95  252460.400   549.80  2009     1
96  310522.592  1037.44  2009     0
97  383635.568  1504.75  2006     0
98  225145.248   648.29  2015     0
99  274922.856   705.29  2006     1

[100 rows x 4 columns]

In [7]:
y=data['price']
x=data[['size','year','view']]

In [8]:
x

size  year  view
0    643.09  2015     0
1    656.22  2009     0
2    487.29  2018     1
3   1504.75  2015     0
4   1275.46  2009     1
..      ...   ...   ...
95   549.80  2009     1
96  1037.44  2009     0
97  1504.75  2006     0
98   648.29  2015     0
99   705.29  2006     1

[100 rows x 3 columns]

In [9]:
reg=LinearRegression()

In [10]:
reg

LinearRegression()

In [11]:
reg.fit(x,y)
reg

LinearRegression()

In [12]:
reg.coef_

array([  223.03161944,  2718.94888864, 56726.01979839])

In [13]:
reg.intercept_

-5397914.181560066

In [14]:
reg.score(x,y)

0.9128639058979641

In [15]:
new_data=pd.DataFrame({'size':[1800,1600,1300],'year':[2016,2020,2040],'view':[0,1,1]})
new_data

size  year  view
0  1800  2016     0
1  1600  2020     1
2  1300  2040     1

In [16]:
result=reg.predict(new_data)
result

array([484943.69292749, 507939.18439182, 495408.67633164])

In [17]:
new_data['prediction']=result
new_data

size  year  view     prediction
0  1800  2016     0  484943.692927
1  1600  2020     1  507939.184392
2  1300  2040     1  495408.676332

### FORMULA FOR ADJUSTED R SQUARE
$R^2_{adj.}=1-(1-R^2)*\frac{n-1}{n-p-1}$

In [19]:
r2=reg.score(x,y)
n=x.shape[0]
p=x.shape[1]


In [20]:
adj_r=1-(1-r2)*(n-1)/(n-p-1)
adj_r

0.9101409029572755

In [25]:
from sklearn.feature_selection import f_regression

In [39]:
f_regression(x,y)

(array([285.92105192,   0.85525799,  20.25908753]),
 array([8.12763222e-31, 3.57340758e-01, 1.86445030e-05]))

In [41]:
p_values=f_regression(x,y)[1]
p_values.round(3)

array([0.   , 0.357, 0.   ])

In [42]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=['features'])
reg_summary

features
0     size
1     year
2     view

In [46]:
reg_summary["Co-efficient"]=reg.coef_
reg_summary['p_values']=p_values.round(3)
reg_summary


features  Co-efficient  p_values
0     size    223.031619     0.000
1     year   2718.948889     0.357
2     view  56726.019798     0.000

In [48]:
new_data1=data[["price","size","view"]]
new_data

size  year  view     prediction
0  1800  2016     0  484943.692927
1  1600  2020     1  507939.184392
2  1300  2040     1  495408.676332

In [50]:
y1=new_data1["price"]
x1=new_data1[["size","view"]]
x1


size  view
0    643.09     0
1    656.22     0
2    487.29     1
3   1504.75     0
4   1275.46     1
..      ...   ...
95   549.80     1
96  1037.44     0
97  1504.75     0
98   648.29     0
99   705.29     1

[100 rows x 2 columns]

In [52]:
from sklearn.preprocessing import StandardScaler

In [54]:
scaler=StandardScaler()

In [56]:
scaler.fit(x1)

StandardScaler()

In [58]:
scaled=scaler.transform(x1)
scaled

array([[-0.70816415, -0.98019606],
       [-0.66387316, -0.98019606],
       [-1.23371919,  1.02020406],
       [ 2.19844528, -0.98019606],
       [ 1.42498884,  1.02020406],
       [-0.937209  ,  1.02020406],
       [-0.95171405,  1.02020406],
       [-0.78328682, -0.98019606],
       [-0.57603328,  1.02020406],
       [-0.53467702, -0.98019606],
       [ 0.69939906, -0.98019606],
       [ 3.33780001,  1.02020406],
       [-0.53467702, -0.98019606],
       [ 0.52699137, -0.98019606],
       [ 1.51100715,  1.02020406],
       [ 1.77668568,  1.02020406],
       [-0.54810263, -0.98019606],
       [-0.77276222,  1.02020406],
       [-0.58004747, -0.98019606],
       [ 0.58943055, -0.98019606],
       [-0.78365788,  1.02020406],
       [-1.02322731, -0.98019606],
       [ 1.19557293,  1.02020406],
       [-1.12884431, -0.98019606],
       [-1.10378093, -0.98019606],
       [ 0.84424715,  1.02020406],
       [-0.95171405,  1.02020406],
       [ 1.62279723,  1.02020406],
       [-0.58004747,

In [60]:
reg1=LinearRegression()

In [62]:
reg1.fit(scaled,y1)

LinearRegression()

In [64]:
reg1.coef_

array([64848.73237624, 28774.16793964])

In [66]:
reg1.intercept_

292289.4701599999

In [68]:
reg1_summary=pd.DataFrame([["bias"],["size"],["view"]],columns=["features"])
reg1_summary['weights']=reg1.intercept_,reg1.coef_[0],reg1.coef_[1]
reg1_summary

features        weights
0     bias  292289.470160
1     size   64848.732376
2     view   28774.167940

In [70]:
new_data=pd.DataFrame({'size':[1800,1600,1300],'view':[0,1,1]})
new_data

size  view
0  1800     0
1  1600     1
2  1300     1

In [72]:
scaled_values=scaler.transform(new_data)
scaled_values


array([[ 3.19440242, -0.98019606],
       [ 2.51974898,  1.02020406],
       [ 1.50776881,  1.02020406]])

In [74]:
reg1.predict(scaled_values)

array([471238.09198244, 485047.52036339, 419421.88943406])